// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvHjV1IThV5UoRqfYii-Pt6Wqo8j1IyM',
    appId: '1:294431355686:web:d30d6ab31378e96cc5c7e7',
    messagingSenderId: '294431355686',
    projectId: 'taskapp-bb28b',
    authDomain: 'taskapp-bb28b.firebaseapp.com',
    storageBucket: 'taskapp-bb28b.appspot.com',
    measurementId: 'G-GKQJNYN8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WW0l2Jz_aYwPCU6dBCtY7UnvD1NI3sM',
    appId: '1:294431355686:android:3bef8daeaeeeb453c5c7e7',
    messagingSenderId: '294431355686',
    projectId: 'taskapp-bb28b',
    storageBucket: 'taskapp-bb28b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNNxEf4A_aHzXMafBFFSRrhPRnu65jt4',
    appId: '1:294431355686:ios:39f6ee145c0a384fc5c7e7',
    messagingSenderId: '294431355686',
    projectId: 'taskapp-bb28b',
    storageBucket: 'taskapp-bb28b.appspot.com',
    iosBundleId: 'com.example.tp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwNNxEf4A_aHzXMafBFFSRrhPRnu65jt4',
    appId: '1:294431355686:ios:f734600c969fa493c5c7e7',
    messagingSenderId: '294431355686',
    projectId: 'taskapp-bb28b',
    storageBucket: 'taskapp-bb28b.appspot.com',
    iosBundleId: 'com.example.tp3.RunnerTests',
  );
}
